{% set name = "napari-segment" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_segment-{{ version }}.tar.gz
  sha256: de092bab18df1980a39fb13dcd4712d9a4c377822cd02d3e62c8023d411ada05

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - imageio-ffmpeg
    - magicgui
    - matplotlib-base
    - napari
    - nd2
    - numpy
    - pandas
    # - pytest-qt  # Not needed
    - python >=3.8
    - pyyaml
    - qtpy
    - scikit-image
    - scipy
    - tifffile
    - zarr

test:
  imports:
    - napari_segment
  commands:
    - pip list
    - pip check || true  # pytest-qt not really needed
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-segment/
  summary: Segment organoids and measure intensities
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/aaristov/napari-segment

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
